// declare module 'vtex.product-context';
// declare module 'vtex.order-items/OrderItems';
// declare module 'vtex.pixel-manager/PixelContext';
// declare module 'vtex.styleguide';
// declare module 'vtex.order-manager';
// declare module 'vtex.pixel-manager';
// declare module 'vtex.render-runtime';
// declare module 'vtex.slider-layout/SliderLayout';
// declare module 'vtex.product-summary-context';
// declare module 'vtex.format-currency'
// declare module 'vtex.css-handles'
// declare module 'vtex.native-types'
